### ISSUE TITLE
テーブル定義書作成

### ISSUE THREAD

**Issue by rtkjm22** [rtkjm22/homeCareNavi_2nd_API#12]
### 概要

テーブル定義書の作成

### テーブル定義書スプシリンク
https://docs.google.com/spreadsheets/d/1yFajwzQAIQ15XBUtTJ0ypM-c8PP6_--PtoGACyVi-A0/edit#gid=1771130073

### 計画

- [x] テーブル数洗い出し
- [x] テーブル一つ修正したら数藤さんにレビューしてもらう
- [ ] ER図作成しながら正規化
- [ ] 再度数藤さんにレビュー
- [ ] 全テーブル修正完了したら石橋さんレビュー
- [ ] 修正無くなればDONE

### 期日
2022/09/02

### 担当
白井

**Comment by cochimu** [comment]
@shota1719 

気になったところ、スプレッドシート 内にコメントしました！

その他全体で聞きたいところ
- 全部のテーブルに作成日時（created_at）と更新日時（udated_at）は入る認識でOKですかね？
- [事業所の施設概要](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/screen/6907b213-a23b-41ef-aba0-bc451eecbf23/)の情報を保存するテーブルがないかもー
- [ユーザーの問い合わせ](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/screen/27f935f4-cd8f-4787-89f5-29a7d0799ee1/)のテーブルがないかもー。この問い合わせは運営への問い合わせなので事業所側も利用者側も両方するはず！
