### ISSUE TITLE
画面一覧の作成（谷川さん）

### ISSUE THREAD

**Issue by rtkjm22** [rtkjm22/homeCareNavi_2nd_API#15]
###概要
フロントエンドのメンバーが主に担当する
画面一覧の作成

担当画面は「ユーザーストーリー」のNo.20〜38まで

期限
7/29(金)

リンク
https://docs.google.com/spreadsheets/d/1bqtMWNMvMhcxZj-SAuPuKpPpgoVKz0GATh2KMEuLtbk/edit#gid=0

ゴール
期限までに画面一覧を作成して、メンバー内で合意を取る

**Comment by marikotanikawa** [comment]
こちらのタスク完了しました！

**Comment by marikotanikawa** [comment]
ご確認ありがとうございます！
そうしましょう🙆‍♀️
よろしくお願いします！
